spring:
  security:
    user:
      name: admin
      password: admin
  ##  database info
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  application:
    name: Solugaz
  jpa:
    ##show-sql: true
    ##  Hibernate DDL create, update...
    hibernate:
      ddl-auto: create
    ## Generation du schemat de la base de donnee;
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
